name: Manual Cypress Tests

on:
  workflow_dispatch:
    inputs:
      site:
        description: "Site to test"
        type: choice
        required: true
        default: all
        options:
          - all
          - home_unificado
          - blpcdpplp
          - blankpage
          - checkout

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      sites: ${{ steps.set-sites.outputs.sites }}
    steps:
      - id: set-sites
        env:
          USER_SITE: ${{ github.event.inputs.site }}
        run: |
          if [[ "$USER_SITE" == "all" ]]; then
            echo 'sites=["home_unificado","blpcdpplp","blankpage","checkout"]' >> "$GITHUB_OUTPUT"
          else
            echo "sites=[\"$USER_SITE\"]" >> "$GITHUB_OUTPUT"
          fi

  cypress-tests:
    needs: set-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        site: ${{ fromJSON(needs.set-matrix.outputs.sites) }}
        device: [samsungA54, iphone11, desktop]

    # 👇 Default working directory for all `run:` steps in this job
    defaults:
      run:
        working-directory: packages/cypress-tests

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        id: cypress
        env:
          SITE: ${{ matrix.site }}
          DEVICE: ${{ matrix.device }}
        run: |
          if [[ "$DEVICE" == "desktop" ]]; then
            browser=firefox
          elif [[ "$DEVICE" == "samsungA54" ]]; then
            browser=chrome
          else
            browser=electron
          fi

          # Run Cypress but DO NOT fail the job yet
          set +e
          npx cypress run --env TAGS=@$SITE,site=$SITE,device=$DEVICE --browser $browser
          EC=$?
          set -e
          echo "exit_code=$EC" >> "$GITHUB_OUTPUT"

      - name: Generate HTML Report
        if: ${{ always() }}
        run: |
          npx mochawesome-merge "cypress/reports/.jsons/*.json" > mochawesome-merged.json
          npx marge mochawesome-merged.json --reportDir "cypress/reports/html"

      # Note: defaults.run doesn't affect action inputs; keep repo-root path here
      - name: Upload HTML report
        if: ${{ always() }}
        id: upload-report
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report-${{ matrix.site }}-${{ matrix.device }}
          path: packages/cypress-tests/cypress/reports/html
          if-no-files-found: warn

      - name: Notify Slack
        if: ${{ always() }}
        env:
          ARTIFACT_URL: ${{ steps.upload-report.outputs.artifact-url }}
          EXIT_CODE: ${{ steps.cypress.outputs.exit_code }}
          SITE: ${{ matrix.site }}
          DEVICE: ${{ matrix.device }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          if [ "$EXIT_CODE" = "0" ]; then
            icon=":white_check_mark:"; result="passed"
          else
            icon=":x:"; result="failed"
          fi
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"${icon} Tests ${result} for ${SITE} on ${DEVICE}: ${ARTIFACT_URL}\"}" \
            "$SLACK_WEBHOOK_URL"

      - name: Fail job if tests failed
        if: ${{ always() && steps.cypress.outputs.exit_code != '0' }}
        run: exit 1
