name: Manual Cypress Tests

on:
  workflow_dispatch:
    inputs:
      site:
        description: 'Site to test'
        type: choice
        required: true
        default: all
        options:
          - all
          - home_unificado
          - blpcdpplp
          - blankpage
          - checkout

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      sites: ${{ steps.set-sites.outputs.sites }}
    steps:
      - id: set-sites
        env:
          USER_SITE: ${{ github.event.inputs.site }}
        run: |
          if [[ "$USER_SITE" == "all" ]]; then
            echo 'sites=["home_unificado","blpcdpplp","blankpage","checkout"]' >> "$GITHUB_OUTPUT"
          else
            echo "sites=[\"$USER_SITE\"]" >> "$GITHUB_OUTPUT"
          fi

  cypress-tests:
    needs: set-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        site: ${{ fromJSON(needs.set-matrix.outputs.sites) }}
        device: [samsungA54, iphone11, desktop]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        # ✅ Ruta correcta, relativa a la raíz del repo
        working-directory: packages/cypress-tests

      - name: Run Cypress tests
        # ✅ Ruta correcta, relativa a la raíz del repo
        working-directory: packages/cypress-tests
        env:
          SITE: ${{ matrix.site }}
          DEVICE: ${{ matrix.device }}
        run: |
          if [[ "$DEVICE" == "desktop" ]]; then
            browser=firefox
          elif [[ "$DEVICE" == "samsungA54" ]]; then
            browser=chrome
          else
            browser=electron
          fi
          npx cypress run --env TAGS=@$SITE,site=$SITE,device=$DEVICE --browser $browser

      - name: Upload HTML report
        if: always()
        id: upload-report
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report-${{ matrix.site }}-${{ matrix.device }}
          # ✅ Ruta correcta, relativa a la raíz del repo
          path: packages/cypress-tests/cypress/reports/html
          if-no-files-found: warn

      # ... el resto del job de Slack no cambia ...
      - name: Notify Slack
        if: always()
        env:
          ARTIFACT_URL: ${{ steps.upload-report.outputs.artifact-url }}
          JOB_STATUS: ${{ job.status }}
          SITE: ${{ matrix.site }}
          DEVICE: ${{ matrix.device }}
        run: |
          if [ "$JOB_STATUS" = "success" ]; then
            icon=":white_check_mark:"
            result="passed"
          else
            icon=":x:"
            result="failed"
          fi
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"${icon} Tests ${result} for ${SITE} on ${DEVICE}: ${ARTIFACT_URL}\"}" \
            https://hooks.slack.com/services/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
